### ISSUE TITLE
需要对/node_modules/axios/lib/adapters/http.js的promise加个catch

### ISSUE THREAD

**Issue by AndrewHann** [Johnserf-Seed/TikTokWeb#14]
解析视频时报错
(node:11901) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/home/pi/TiktokWeb/web/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/TiktokWeb/web/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/TiktokWeb/web/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by michael2221807** [comment]
一样的问题，请问老哥你解决了吗？

**Comment by AndrewHann** [comment]
> 一样的问题，请问老哥你解决了吗？

解决方式我已经写在标题上了呀，直接对这个promise加个catch就可以了

**Comment by lazyou** [comment]
为什么会产生403？是cookie无效吗，我不少视频都无法解析

**Comment by AndrewHann** [comment]
> 

我也会这样 多试几次就行了

**Comment by zuimengxinbie** [comment]
什么垃圾

**Comment by 18639522576** [comment]
加上catch 也是解析不了  是不是失效了

**Comment by Johnserf-Seed** [comment]
使用新镜像即可
