### ISSUE TITLE
404 走丢啦 这不是你该来的地方

### ISSUE THREAD

**Issue by hechuan4** [Johnserf-Seed/TikTokWeb#21]
那里的问题？

root@localhost:~/TikTokWeb# npm start http://localhost:4000/

> tiktokweb@0.0.0 start
> nodemon ./bin/www "http://localhost:4000/"

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www http://localhost:4000/`
GET / 304 34.103 ms - -
GET /static/stylesheets/milligram.min.css 304 11.155 ms - -
GET /static/stylesheets/progress.css 304 4.214 ms - -
GET /static/stylesheets/unicons.css 304 4.068 ms - -
GET /static/javascripts/jquery.cookie.min.js 200 57.229 ms - 1301
GET /static/javascripts/jquery.min.js 200 53.901 ms - 89795
GET /static/javascripts/jszip.min.js 200 69.167 ms - 97630
GET /static/javascripts/FileSaver.min.js 200 58.540 ms - 2749
GET /static/javascripts/progress.js 200 59.108 ms - 1321
GET /static/fonts/unicons.woff2 200 7.955 ms - 143000
{"odin_tt":"94709eec8aca4ab392e54ba33aced8f191590dd11d625e62493fc2152b1e72174d3f274b2a1e53059921090ad7517d62ae93","passport_csrf_token":"d529c6921bf2090e4192f72d56ac","sessionid_ss":"ad8f2b679ffb4fcc101eab54541432e0\t","ttwid":"verify_lj870qjm_CG0sJlEa_Bo0w_4qG5_BLF8_BaG7u6o3M3RR","msToken":"VF1Vy74v2AeVIEIg6YXlodhMB6P-5BOKVuBxggDSdyNVxRBCJOLtJwgNw_D8er3mEjma3eTuO0SVJlLyh5w=="}
open shorturl ok
作品id  7086787906316094735
https://www.douyin.com/aweme/v1/web/aweme/detail/?aweme_id=7086787906316094735&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333&X-Bogus=DFSzswVuTzGANxXhtn4hKl9WX7jQ
open url ok
GetInfo ok
TypeError: response.data.aweme_detail.desc.replaceAll is not a function
    at /root/TikTokWeb/routes/api.js:97:68
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
TypeError: response.data.aweme_detail.desc.replaceAll is not a function
    at /root/TikTokWeb/routes/api.js:97:68
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
GET /api?url=https://v.douyin.com/NKyY6Ch/ 304 20800.254 ms - -
(node:12293) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at GetInfo (/root/TikTokWeb/routes/api.js:127:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/root/TikTokWeb/node_modules/express/lib/response.js:794:10)
    at ServerResponse.contentType (/root/TikTokWeb/node_modules/express/lib/response.js:624:15)
    at ServerResponse.send (/root/TikTokWeb/node_modules/express/lib/response.js:149:14)
    at done (/root/TikTokWeb/node_modules/express/lib/response.js:1035:10)
    at tryHandleCache (/root/TikTokWeb/node_modules/ejs/lib/ejs.js:280:5)
    at View.exports.renderFile [as engine] (/root/TikTokWeb/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/root/TikTokWeb/node_modules/express/lib/view.js:135:8)
    at tryRender (/root/TikTokWeb/node_modules/express/lib/application.js:657:10)
    at Function.render (/root/TikTokWeb/node_modules/express/lib/application.js:609:3) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/root/TikTokWeb/node_modules/express/lib/response.js:794:10)
    at ServerResponse.contentType (/root/TikTokWeb/node_modules/express/lib/response.js:624:15)
    at ServerResponse.send (/root/TikTokWeb/node_modules/express/lib/response.js:149:14)
    at done (/root/TikTokWeb/node_modules/express/lib/response.js:1035:10)
    at tryHandleCache (/root/TikTokWeb/node_modules/ejs/lib/ejs.js:280:5)
    at View.exports.renderFile [as engine] (/root/TikTokWeb/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/root/TikTokWeb/node_modules/express/lib/view.js:135:8)
    at tryRender (/root/TikTokWeb/node_modules/express/lib/application.js:657:10)
    at Function.render (/root/TikTokWeb/node_modules/express/lib/application.js:609:3)
GET /static/stylesheets/404.css 304 4.661 ms - -

**Comment by hechuan4** [comment]
root@localhost:~/TikTokWeb# nrm ls
  npm ---------- https://registry.npmjs.org/
  yarn --------- https://registry.yarnpkg.com/
* tencent ------ https://mirrors.cloud.tencent.com/npm/
  cnpm --------- https://r.cnpmjs.org/
  taobao ------- https://registry.npmmirror.com/
  npmMirror ---- https://skimdb.npmjs.com/registry/
root@localhost:~/TikTokWeb# 

换源了

**Comment by jophone** [comment]
我也遇到这个问题。。

**Comment by Johnserf-Seed** [comment]
使用新镜像即可

**Comment by qs-lll** [comment]
最新版本的docker  无法使用  404
