### ISSUE TITLE
长视频无法下载？

### ISSUE THREAD

**Issue by jas0ndyq** [Johnserf-Seed/TikTokWeb#30]
示例视频链接：https://v.douyin.com/ieofmV5v/ 

后台异常如下：

TypeError: Cannot read property 'play_url' of undefined
    at GetInfo (D:\Softwares\TikTok\TikTokWeb-main\utils\douyinService.js:78:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async D:\Softwares\TikTok\TikTokWeb-main\routes\api.js:40:27
GET /api?url=https://v.douyin.com/ieofmV5v/ 500 963.420 ms - 861

**Comment by Johnserf-Seed** [comment]
长视频可以下载，这个问题是接口没有找到视频地址
