### ISSUE TITLE
npm start 出错

### ISSUE THREAD

**Issue by victpa** [Johnserf-Seed/TikTokWeb#5]
root@localhost:~/TikTokWeb# npm start

> tiktokweb@0.0.0 start /root/TikTokWeb
> nodemon ./bin/www

/root/TikTokWeb/node_modules/update-notifier/index.js:58
                        } catch {
                                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/TikTokWeb/node_modules/nodemon/bin/nodemon.js:15:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiktokweb@0.0.0 start: `nodemon ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiktokweb@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-30T14_09_21_009Z-debug.lo
[2022-04-30T13_59_12_853Z-debug.log](https://github.com/Johnserf-Seed/TikTokWeb/files/8597083/2022-04-30T13_59_12_853Z-debug.log)
g

**Comment by Johnserf-Seed** [comment]
1、删除node_modules文件夹
2、更改为国内npm源
3、重新npm i
4、 npm start

**Comment by Johnserf-Seed** [comment]
> 1、删除node_modules、package-lock.json 2、更改为国内npm源 3、重新npm i 4、 npm start

**Comment by Johnserf-Seed** [comment]
使用新镜像即可
